using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Editor window for generating and editing enums in Unity
/// </summary>
public class EnumGeneratorWindow : EditorWindow
{
    #region Variables
    private string enumName = "TypeOfEnvironmentCharacteristic";
    private string folderPath = "Assets/Scripts/Generated";
    private List<string> elements = new List<string> { "Default", "Null" };
    private Vector2 scrollPos;
    #endregion

    #region Unity Methods
    /// <summary>
    /// Opens the Enum Generator window
    /// </summary>
    [MenuItem("Tools/Enum Generator")] 
    public static void OpenWindow()
    {
        GetWindow<EnumGeneratorWindow>("Enum Generator");
    }

    private void OnGUI()
    {
        GUILayout.Label("🧱 Enum Generator and Editor", EditorStyles.boldLabel);
        GUILayout.Space(10);
        
        if (GUILayout.Button("📂 Load Existing Enum...", GUILayout.Height(25)))
        {
            LoadExistingEnum();
        }

        GUILayout.Space(10);
        
        enumName = EditorGUILayout.TextField("Enum Name", enumName);
        
        EditorGUILayout.BeginHorizontal();
        EditorGUILayout.PrefixLabel("Output Folder");
        EditorGUILayout.SelectableLabel(folderPath, GUILayout.Height(16));
        if (GUILayout.Button("Select...", GUILayout.Width(100)))
        {
            string selected = EditorUtility.OpenFolderPanel("Select output folder", "Assets", "");
            if (!string.IsNullOrEmpty(selected))
            {
                if (selected.StartsWith(Application.dataPath))
                    folderPath = "Assets" + selected.Substring(Application.dataPath.Length);
                else
                    EditorUtility.DisplayDialog("Warning", "Please select a folder inside 'Assets'!", "OK");
            }
        }

        EditorGUILayout.EndHorizontal();

        GUILayout.Space(10);
        GUILayout.Label("Enum Elements:", EditorStyles.boldLabel);
        
        scrollPos = EditorGUILayout.BeginScrollView(scrollPos, GUILayout.Height(150));
        for (int i = 0; i < elements.Count; i++)
        {
            EditorGUILayout.BeginHorizontal();
            elements[i] = EditorGUILayout.TextField(elements[i]);
            if (GUILayout.Button("X", GUILayout.Width(25)))
            {
                elements.RemoveAt(i);
                i--;
            }

            EditorGUILayout.EndHorizontal();
        }

        EditorGUILayout.EndScrollView();

        if (GUILayout.Button("+ Add Element"))
            elements.Add("NewElement");

        GUILayout.Space(15);

        GUI.enabled = !string.IsNullOrEmpty(enumName) && elements.Count > 0;
        if (GUILayout.Button("📜 Generate Enum", GUILayout.Height(30)))
        {
            GenerateEnumFile();
        }

        GUI.enabled = true;
    }
    #endregion

    #region File Generation
    /// <summary>
    /// Generates the enum file with the specified name and elements
    /// </summary>
    private void GenerateEnumFile()
    {
        if (string.IsNullOrEmpty(enumName))
        {
            EditorUtility.DisplayDialog("Error", "Enum name cannot be empty.", "OK");
            return;
        }

        if (elements.Count == 0)
        {
            EditorUtility.DisplayDialog("Error", "Elements list cannot be empty.", "OK");
            return;
        }

        if (!Directory.Exists(folderPath))
            Directory.CreateDirectory(folderPath);

        string filePath = Path.Combine(folderPath, $"{enumName}.cs");

        using (StreamWriter writer = new StreamWriter(filePath))
        {
            writer.WriteLine("// Automatically generated by EnumGeneratorWindow");
            writer.WriteLine($"public enum {enumName}");
            writer.WriteLine("{");
            foreach (string element in elements)
            {
                if (!string.IsNullOrWhiteSpace(element))
                {
                    string cleanName = MakeSafeIdentifier(element);
                    writer.WriteLine($"    {cleanName},");
                }
            }
            writer.WriteLine("}");
        }

        AssetDatabase.Refresh();
        EditorUtility.DisplayDialog("✅ Success", $"Enum '{enumName}' generated or updated at:\n{filePath}", "OK");
    }
    #endregion

    #region File Operations
    /// <summary>
    /// Loads an existing enum file for editing
    /// </summary>
    private void LoadExistingEnum()
    {
        string path = EditorUtility.OpenFilePanel("Select enum file", Application.dataPath, "cs");
        if (string.IsNullOrEmpty(path))
            return;

        string content = File.ReadAllText(path);
        string relative = path.Replace(Application.dataPath, "Assets");


        Match nameMatch = Regex.Match(content, @"public\s+enum\s+(\w+)");
        if (nameMatch.Success)
            enumName = nameMatch.Groups[1].Value;
        
        Match bodyMatch = Regex.Match(content, @"{([^}]*)}");
        if (bodyMatch.Success)
        {
            string body = bodyMatch.Groups[1].Value;
            string[] lines = body.Split(new[] { '\n', '\r', ',' }, System.StringSplitOptions.RemoveEmptyEntries);
            elements.Clear();
            foreach (var line in lines)
            {
                string clean = line.Trim();
                if (!string.IsNullOrEmpty(clean) && !clean.StartsWith("//"))
                    elements.Add(clean);
            }
        }


        folderPath = Path.GetDirectoryName(relative).Replace("\\", "/");

        EditorUtility.DisplayDialog("✅ Enum Loaded", $"Enum '{enumName}' loaded successfully!", "OK");
    }
    #endregion

    #region Utilities
    /// <summary>
    /// Converts a string into a valid C# identifier
    /// </summary>
    /// <param name="name">The string to convert</param>
    /// <returns>A valid C# identifier</returns>
    private string MakeSafeIdentifier(string name)
    {
        string safe = name.Trim().Replace(" ", "_").Replace("-", "_");
        if (safe.Length > 0 && char.IsDigit(safe[0]))
            safe = "_" + safe;
        return safe;
    }
    #endregion
}