// Automatically generated by EnumGeneratorWindow
namespace MyEnum
{
 public enum SpawnerCharacterEnum
  {
     QE1,
     QE2,
     QB1,
     QB2,
     QB3,
     QF,
     AC,
     QT,
     SA,
     B,
  }
}
